apiVersion: v1
kind: Service
metadata:
  labels:
    app: urs-web
  name: urs-web
spec:
  ports:
  - name: http
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: urs-web
  type: ClusterIP
