apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: urs-proxy
  name: urs-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urs-proxy
  template:
    metadata:
      labels:
        app: urs-proxy
    spec:
      containers:
        - name: urs-proxy
          image: 765528283900.dkr.ecr.us-west-2.amazonaws.com/urs-proxy:1.1.0.6
          imagePullPolicy: IfNotPresent
          env:
            - name: env.profile
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: env.profile
            - name: spring.data.redis.host
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: spring.data.redis.host
            - name: spring.data.redis.timeout
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: spring.data.redis.timeout
            - name: tunnel.host
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: tunnel.host
            - name: spring.cloud.kubernetes.discovery.namespaces
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: spring.cloud.kubernetes.discovery.namespaces
