apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: urs-tunnel-manager
  name: urs-tunnel-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: urs-tunnel-manager
  template:
    metadata:
      labels:
        app: urs-tunnel-manager
    spec:
      containers:
        - name: urs-tunnel-manager
          image: 765528283900.dkr.ecr.us-west-2.amazonaws.com/urs-tunnel-manager:1.1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: env.profile
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: env.profile
            - name: spring.data.redis.host
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: spring.data.redis.host
            - name: spring.data.redis.timeout
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: spring.data.redis.timeout
            - name: tunnel.host
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: tunnel.host
            - name: spring.cloud.kubernetes.discovery.namespaces
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: spring.cloud.kubernetes.discovery.namespaces
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
