apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: urs-web-blue
  name: urs-web-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urs-web-blue
  template:
    metadata:
      labels:
        app: urs-web-blue
    spec:
      containers:
        - name: urs-web-blue
          image: 765528283900.dkr.ecr.us-west-2.amazonaws.com/urs-web:79-r1
          imagePullPolicy: IfNotPresent
          env:
            - name: release.version
              value: 1.0.0.79-r1
            - name: env.profile
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: env.profile
            - name: mfa.enable
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: mfa.enable
            - name: spring.data.redis.host
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: spring.data.redis.host
            - name: spring.data.redis.timeout
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: spring.data.redis.timeout
            - name: system.code
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: system.code.blue
            - name: service.domain
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: service.domain.blue
            - name: service.cookie.domain
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: service.cookie.domain.blue
            - name: spring.cloud.kubernetes.discovery.namespaces
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: spring.cloud.kubernetes.discovery.namespaces
            - name: aws.cognito.region
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: aws.cognito.region.blue
            - name: aws.cognito.clientId
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: aws.cognito.clientId.blue
            - name: aws.cognito.pool-id
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: aws.cognito.pool-id.blue
            - name: aws.cognito.user-pool-domain
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: aws.cognito.user-pool-domain.blue
            - name: email.service.smtp
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: email.service.smtp.blue
            - name: email.service.auth
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: email.service.auth.blue
            - name: email.service.port
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: email.service.port.blue
            - name: email.service.starttls.enable
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: email.service.starttls.enable.blue
            - name: email.service.ssl.enable
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: email.service.ssl.enable.blue
            - name: email.service.userName
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: email.service.userName.blue
            - name: email.service.password
              valueFrom:
                secretKeyRef:
                  name: urs-secret
                  key: email.service.password.blue
            - name: spring.security.oauth2.client.registration.cognito.clientId
              valueFrom:
                configMapKeyRef:
                  name: urs-config
                  key: aws.cognito.clientId.blue
            - name: spring.security.oauth2.client.registration.cognito.clientSecret
              valueFrom:
                secretKeyRef:
                  name: urs-secret
                  key: cognito.clientSecret.blue
            - name: aws.access_key_id
              valueFrom:
                secretKeyRef:
                  name: urs-secret
                  key: aws.access_key_id
            - name: aws.secret_access_key
              valueFrom:
                secretKeyRef:
                  name: urs-secret
                  key: aws.secret_access_key
