apiVersion: v1
kind: Service
metadata:
  labels:
    app: urs-scheduler
  name: urs-scheduler
spec:
  ports:
    - port: 8702
      protocol: TCP
      targetPort: 8702
  selector:
    app: urs-scheduler
  type: ClusterIP
