apiVersion: v1
kind: Service
metadata:
  labels:
    app: urs-management
  name: urs-management
spec:
  ports:
    - port: 8071
      protocol: TCP
      targetPort: 8071
  selector:
    app: urs-management
  type: ClusterIP
