apiVersion: v1
kind: Service
metadata:
  labels:
    app: urs-agent
  name: urs-agent
spec:
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app: urs-agent
  type: ClusterIP

