apiVersion: v1
kind: Service
metadata:
  labels:
    app: urs-maintenance
  name: urs-maintenance
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: urs-maintenance
  type: ClusterIP
